---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lightspeed-exporter-config-stage
  namespace: lsdv-exporter
data:
  config.yaml: |
    # Stage environment configuration - uses manual mode with explicit tokens
    data_dir: "/data"
    service_id: "ols"
    ingress_server_url: "https://console.stage.redhat.com/api/ingress/v1/upload"
    
    # Auth token and identity_id provided explicitly for stage environment
    # These will be overridden by command line args or environment variables
    ingress_server_auth_token: "PLACEHOLDER_TOKEN"
    identity_id: "PLACEHOLDER_IDENTITY"
    
    # Collection settings
    collection_interval: 300  # 5 minutes
    cleanup_after_send: false # keep false to avoid permission errors with read-only test data
    ingress_connection_timeout: 30
  
  # Sample data for testing
  sample-lightspeed-data.json: |
    {
      "user_id": "user_id_placeholder",
      "timestamp": "2025-07-24 13:16:49.140050+00:00",
      "conversation_id": "123e4567-e89b-12d3-a456-426614174000",
      "user_question": "What is XYZ",
      "llm_response": "Some elaborate answer",
      "sentiment": 1,
      "user_feedback": ""
    } 