---
apiVersion: batch/v1
kind: Job
metadata:
  name: lightspeed-exporter-test-prod
  namespace: lsdv-exporter
  labels:
    app: lightspeed-exporter
    type: test
    environment: prod
spec:
  template:
    metadata:
      labels:
        app: lightspeed-exporter
        type: test
        environment: prod
    spec:
      serviceAccountName: lightspeed-exporter
      containers:
      - name: lightspeed-exporter
        # Update this image when you push to your registry
        image: "quay.io/ometelka/lightspeed-dataverse-exporter:latest"
        imagePullPolicy: Always
        command: ["python", "-m", "src.main"]
        args:
        - "--mode"
        - "openshift"
        - "--config"
        - "/etc/config/config.yaml"
        - "--log-level"
        - "INFO"
        - "--collection-interval"
        - "7200"  # Production interval (2 hours)
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: data
          mountPath: /data
        # Note: No sample data mount in production - real data should be provided via proper data volume
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: UV_CACHE_DIR
          value: "/tmp/uv-cache"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: lightspeed-exporter-config-prod
      - name: data
        emptyDir: {}
      # Note: No sample-data volume in production
      restartPolicy: Never
  backoffLimit: 3 